### PR TITLE
do not render table with if no fields or rows

### LINKED ISSUE #573: Blank Screen Make App Unusable
Some querys when performed causes the app to crash, also running CTRL+R or CTRL+ENTER have the same problem sometimes.
I am using Linux POP!_OS 20.04 LTS, but I have the same problem on a Windows 10 machine too.
image
image

### PR DESCRIPTION
**Pull request by MasterOdin**
Fixes #573

This fixes the crash where on running a query that's not recognized, but also returns an empty resultset, the app would crash. Now, we'll just print a nice generic "Query success" type message in-lieu of anything better.

### CODE REVIEW

File: src/renderer/components/query-result.jsx [hunk 1]
```diff
@@ -75,14 +75,26 @@ export default class QueryResult extends Component {
...
+    // generic message.
+    if (fields.length === 0) {
+      return (
+        <Message
+          key={`genericResult-${queryIndex}`}
+          message={`Query executed successfully.`}
+          type="success"
+        />
+      );
+    }
```
Comment (MasterOdin) [inline src/renderer/components/query-result.jsx:96]: I put this `if` statement here (as opposed to high-up as possible) to act as a final catch-all before rendering the table, and that we may add to the the possible conditions in which we enter this if statement, and do not want to worry about colliding with `explain` or anything else we might put above it,

**Review by maxcnunes — APPROVED** [review]
Good catch
