### PR TITLE
Fix error on starting sqlectron with no config file

### LINKED ISSUE #596: Cannot read property 'level' of undefined
While using ```npm run dev``` on source code  it gives this error ```Cannot read property 'level' of undefined```

error
```
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
```

full log
```
> sqlectron@1.35.0 dev C:\learnElectron\sqlectron-gui
> cross-env NODE_ENV=development concurrently --names "webpack,electron" --prefix name "npm run dev:webpack" "npm run dev:electron"

[webpack] 
[webpack] > sqlectron@1.35.0 dev:webpack C:\learnElectron\sqlectron-gui
[webpack] > webpack-dev-server --color
[webpack]
[electron] 
[electron] > sqlectron@1.35.0 dev:electron C:\learnElectron\sqlectron-gui
[electron] > npm run compile:browser && concurrently --kill-others --names "build,run" "npm run compile:browser -- -w" "cross-env DEBUG=spawn-auto-restart node scripts/dev-auto-restart.js | bunyan -o short"
[electron]
[electron] 
[electron] > sqlectron@1.35.0 compile:browser C:\learnElectron\sqlectron-gui
[electron] > tsc --project tsconfig.build.json
[electron]
[webpack] i ｢wds｣: Project is running at http://localhost:8080/
[webpack] i ｢wds｣: webpack output is served from /static/
[webpack] i ｢wds｣: Content not from webpack is served from C:\learnElectron\sqlectron-gui
[electron] [1] Not watching changes on sqlectron-db-core
[electron] [1]
[electron] [0]
[electron] [0] > sqlectron@1.35.0 compile:browser C:\learnElectron\sqlectron-gui
[electron] [0] > tsc --project tsconfig.build.json "-w"
[electron] [0]
[electron] [0]
[electron] [0] 4:44:15 pm - Starting compilation in watch mode...
[electron] [0]
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[webpack] Browserslist: caniuse-lite is outdated. Please run:
[webpack] npx browserslist@latest --update-db
[electron] [1] 2021-03-09T11:14:21.521Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.578Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.609Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.665Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.691Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.696Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.724Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.726Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.752Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.755Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.757Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.783Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.785Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.813Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.816Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.839Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [1] 2021-03-09T11:14:21.847Z spawn-auto-restart restarting due changes
[electron] [0] 
[electron] [0] 4:44:21 pm - Found 0 errors. Watching for file changes.
[electron] [1] 
[electron] [1] App threw an error during load
[electron] [1] TypeError: Cannot read property 'level' of undefined
[electron] [1]     at Object.getConfig (C:\learnElectron\sqlectron-gui\out\browser\config.js:64:34)
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\out\browser\main.js:24:27)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[electron] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[electron] [1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[electron] [1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[electron] [1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[electron] [1]     at loadApplicationPackage (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)        
[electron] [1]     at Object.<anonymous> (C:\learnElectron\sqlectron-gui\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
[electron] [1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[webpack] i ｢wdm｣: Hash: 8daa266775b9db31f885
[webpack] Version: webpack 4.44.1
[webpack] Time: 15359ms
[webpack] Built at: 09/03/2021 4:44:24 pm
[webpack]                                                                        Asset      Size  Chunks             Chunk Names
[webpack]                         _/vendor/renderer/lato/fonts/Lato-Regular-19df47.eot   248 KiB          [emitted]
[webpack]                        _/vendor/renderer/lato/fonts/Lato-Regular-1d2ca9.woff   302 KiB          [emitted]
[webpack]                       _/vendor/renderer/lato/fonts/Lato-Regular-75614c.woff2   178 KiB          [emitted]
[webpack]                         _/vendor/renderer/lato/fonts/Lato-Regular-bb14dc.ttf   593 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-03605b.eot  59.3 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-45f9f9.ttf   119 KiB          [emitted]
[webpack]  _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-c589f7.woff  69.8 KiB          [emitted]
[webpack]   _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-d0ba16.svg   306 KiB          [emitted]
[webpack] _/vendor/renderer/semantic-ui/themes/default/assets/fonts/icons-fb685a.woff2  55.4 KiB          [emitted]
[webpack]                                                                    bundle.js  27.5 MiB     app  [emitted]  app
[webpack]                                                                   index.html  2.17 KiB          [emitted]
[webpack] Entrypoint app = bundle.js
[webpack] [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/renderer/entry.tsx 52 bytes {app} [built]
[webpack] [./node_modules/react-dom/index.js] 1.33 KiB {app} [built]
[webpack] [./node_modules/react-redux/es/index.js] 776 bytes {app} [built]
[webpack] [./node_modules/react-router/es/index.js] 1.43 KiB {app} [built]
[webpack] [./node_modules/react/index.js] 190 bytes {app} [built]
[webpack] [./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built] 
[webpack] [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[webpack] [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} [built]        
[webpack] [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[webpack] [./src/renderer/entry.tsx] 1.3 KiB {app} [built]
[webpack]     + 585 hidden modules
[webpack] Child HtmlWebpackCompiler:
[webpack]      1 asset
[webpack]     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[webpack]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/renderer/index.html] 2.6 KiB {HtmlWebpackPlugin_0} [built]
[webpack] i ｢wdm｣: Compiled successfully.
```

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #596

When sqlectron is started for the first time with an empty config file, a number of errors are thrown, namely that:
* servers does not exist, throwing an "map on undefined" error
* log.level does not exist, throwing an "level on undefined" error

To capture the behavior here that much of the config file is optional, I've introduced a new type "ConfigFile", where then "Config" is a concrete implementation within the GUI itself after loading the file. I've also made the utils functions more generic as they could work on anything really, not just Config objects.

### CODE REVIEW

File: src/common/types/config.ts [hunk 1]
```diff
@@ -1,5 +1,25 @@
 import { Server } from './server';
 
+export interface ConfigFile {
```
Comment (maxcnunes) [inline src/common/types/config.ts:3]: Since there are 2 very similar interfaces, could you please add a comment for each one of them explaining what they are used for and their differences?

**Review by maxcnunes — COMMENTED** [review]
Not sure if we really needed a new interface for the ConfigFile, since we could just change the initial value to capture all required fields. But I don't have strong opinion against it though, so that is fine I just think we need to document better their differences.

**Comment by MasterOdin** [comment]
> Not sure if we really needed a new interface for the ConfigFile, since we could just change the initial value to capture all required fields. But I don't have strong opinion against it though, so that is fine I just think we need to document better their differences.

Yeah, so at least up to 1.35.0, the sqlectron.json file will always have at least `servers`. All other elements are optional. I think we either need to capture this within an interface (what I've done here), or expand the set of items so that the `Config` interface matches what we get from the file in all cases. I would prefer to probably keep the config file working the same just to be more "BC friendly", and so add the new interface to accurately capture what the config file may hold.

File: src/common/types/config.ts (hunk 1 above)
Comment (MasterOdin) [reply src/common/types/config.ts:8]: done.

File: src/common/types/config.ts [hunk 2]
```diff
@@ -1,5 +1,35 @@
 import { Server } from './server';
 
+/**
+ * This interface documents the sqlectron.json file. The only thing guaranteed to
+ * exist is the `servers` key/value pair (instantiated to empty array). The rest
+ * will only exist if the user goes into the Settings modal and hits save.
+ */
+export interface ConfigFile {
```
Comment (maxcnunes) [inline src/common/types/config.ts:8]: @MasterOdin wondering if wouldn't be better to make `Config` extend `ConfigFile` to avoid duplicated fields, event though most base fields are optional.

**Review by maxcnunes — APPROVED** [review]
Left a comment, but LGTM as is as well if you rather not apply that change.
